Chore(demo): Switch from `react-docgen-typescript` to `react-docgen`
  * with new Storybook versions the preview and the build were not able to run
  * `error TS5083: Cannot read file './tsconfig.json'.`
  * @see: https://github.com/storybookjs/storybook/issues/29828#issuecomment-2590263364