Chore(repo): Pin typescript to version 4.8.2
  * disable automatic upgrading of typescript due to an issue with
    popper-js-core which is used by Storybook
  * eg.: Error: ../../node_modules/@storybook/components/dist/ts3.9/_modules
         /@popperjs-core-lib-types.d.ts(123,34): error TS2344:
         Type 'Options' does not satisfy the constraint 'Obj'.